language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master
script:
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id:
    secure: e999TwuE+HVUDdysU7POsA0obxBOjq+1+FE7z//CRj1caKqp22FjtRFhqeA9s5p1PQZujZsBmWv0U4hkOMuOGx+zVDC4v4Lu9LYRn0/7UE/BXwA8RbpxF4M/B3SAfZIt1VsSrIsatwhUsCCwKxeotmZ9j9Dgg5+xmdaJe3o6W29KbeVDvqAB90N7atJ2wp1d6OSOeSCrPucT6PUhfsuPH8rDQOEI42FWr86wts0m3YAZ570Sdr4byVZAabzt33fchK1r+/9x9GGKuoEcuSuHrtckFYtHykuUrHyavyjQAmT4I5d+2fXszLJTLmAD7oKp9QXulCBQdl/aTM4i0SGyMTZjL4tXok+OF/NAkh2jv/rn7k2sMLL5xa9ysPWeNRmLy5Wwv76GuJL/WSGBDpo5w/nk7Cljk8NzvQOi6mHb/0hb3RLgGtbNcJ46lf+hiqGrMeHmuXyQqdvfDXzTcN81BicObMclQhCO4Z4YytQSctMpKYUpxEhgX9hVesLKoA11Jhzj+IkIXQQsBxcozBK2BPPeFLfhMiyIaf3/8QVxoBNVSQO87zolHn9LrS25g0GqXTcoMWydNfJefzgwRBoLmXo5vcGEnArbgRCIkh2VjPD+1aczJLOLM4I9Dk88amKUiKRcVsr4NyUkmi5ml2OGsJbYi2A8Kljf4GfJCKeloDw=
  secret_access_key:
    secure: Tfvxy/egoFjwq299eXczGNlL6hUM+JOh2XslFKvdq/TkjT9lVI4Ru/Gf40K3itqu0M5eib0rb13KJPBjy+YAfT+hIR3jdKXoWRUoWZYksbs/W+uwrFYiL5s0M2zO21rv18e6xrPmJZx5G8Y5P6NhfQvjdbnxazTHTw+TugZw+dr5wFAP3udwJmSIlgH155K5X4aBWhFaRIgsrpLTHPFd+q495JTb1+b3sZf7qBzL8DHrFo6YCSNeU92AW0XtajJ1SDtwAy3/YwLZcqltZIG91dXcBISk/qYmnKjcwpT/u2qUq+GhD882nntegUzWF8NG89x9VXxtl5YBaru666bCJlv2eJc2FEXbvSIFktVDLgE8OJVm7zXwS8unjtkvndDY+tmJjxjwuaTNdAjxXAqFZx7BLZsK+0P3U1GpBKknqOfV88W5S47Cxdgd0a1TY5vsd5y3JmTZb3PFu/P9sQhQRFEjKuFnnihpUdX+Y4134Gp3mRvom9GhsCk0gnjxxHehOzDqALlzHTmmX8vfUeD5Rj0vsRVA/Sfih3nUsOMKxXJBUOGvl/IQGoTxO0LiMIflo6F1Z4pH7d8HtHBfZKvlrTpt3kI342rW3/bRrOLnnZdLwh/7kbzYGvJzeIuUGDzNlABhV9XUlnmsOJJ5q5rWY8eoXtn+EoG1SUwIj6WdVQI=
  bucket: mikroways.net
  local-dir: _site
  acl: public_read
