language: ruby
cache: bundler
rvm:
- 2.2
branches:
  only:
  - master
script:
- bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY_ID
  region: $AWS_REGION
  bucket: mikroways.net
  local_dir: _site/
  acl: public_read
